config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :channels
  resources :messages

  root to: "channels#index"

end

app/models/chat_room.rb
# == Schema Information
#
# Table name: chat_rooms
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ChatRoom < ActiveRecord::Base
  has_many :messages
  has_many :users
end

app/models/chat_room_user.rb
# == Schema Information
#
# Table name: chat_room_users
#
#  id           :integer          not null, primary key
#  chat_room_id :integer
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ChatRoomUser < ActiveRecord::Base
  belongs_to :chat_room
  belongs_to :user
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  content      :text
#  chat_room_id :integer
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Message < ActiveRecord::Base
  belongs_to :chat_room
  belongs_to :user

  def as_json(options={})
    {
      id: self.id,
      content: self.content,
      user_email: self.user.email,
      username: self.user.username,
      avatar_url: self.user.avatar_url
    }
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string
#  avatar_url             :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @channels = ChatRoom.all
  end

  def create
  end

  def new
  end

  def destroy
  end

  def show
    @channel = ChatRoom.find params[:id]
    @channel_users = ChatRoomUser.where(chat_room_id: @channel.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = Message.where('id > ?', params[:after_id].to_i).order('created_at DESC')
  end

  def create
    respond_to do |format|
      @message = current_user.messages.build(message_params)
      if @message.save
        flash.now[:success] = 'Your message was successfully posted!'
      else
        flash.now[:error] = 'Your message cannot be saved.'
      end
      format.html {redirect_to new_message_path}
      format.js
    end
  end

  def new
    @message = Message.new
    @messages = Message.order('created_at DESC')
  end

  def destroy
  end

  def show
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/channels/create.html.erb
<h1>Channels#create</h1>
<p>Find me in app/views/channels/create.html.erb</p>

app/views/channels/destroy.html.erb
<h1>Channels#destroy</h1>
<p>Find me in app/views/channels/destroy.html.erb</p>

app/views/channels/index.html.haml
%h1
  List of Channels
- @channels.each do |channel|
  .well
    = link_to channel.name, channel_path(channel)

app/views/channels/new.html.erb
<h1>Channels#new</h1>
<p>Find me in app/views/channels/new.html.erb</p>

app/views/channels/show.html.haml
.left-sidebar
  %h1.title#current-channel{"data-id" => @channel.id}
    = @channel.name
  %ul
  - @channel_users.each do |channel_user|
    %li
      - if channel_user.user.email == current_user.email
        %div#current-user{"data-username" => current_user.username, "data-email" => current_user.email, "data-id" => current_user.id}
      = channel_user.user.username
.right-area
  .chat-header
    %h2
      Chat Header!
  #area-chat
    - @channel.messages.each do |message|
      .chat-row
        .messages{"data-id" => message.id}
          %img{src: message.user.avatar_url}
          %b
            = "#{message.user.username} "
          .message
            = message.content
  .text-input
    %input.form-control#text-chat{type:"text"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SlackClone
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if notice
      %p.notice= notice
    - elsif alert
      %p.alert= alert
    = yield

app/views/messages/_form.html.erb
<div class="well">
  <%= form_for @message, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :content, 'Enter your comment:' %>
      <%= f.text_area :content, rows: 3, class: 'form-control', required: true, maxlength: 2000 %>
      <small class="label label-warning">Cannot be blank or contain more than 2000 symbols.</small>
    </div>

    <%= f.submit 'Post', class: 'btn btn-primary btn-lg' %>
  <% end %>
</div>

app/views/messages/_message.html.erb
<li class="media message" data-id="<%= message.id %>">
  <%= link_to image_tag(message.user.avatar_url, alt: message.user.username, class: "media-object"), "#", target: '_blank', class: 'pull-left' %>
  <div class="media-body">
    <h4 class="media-heading"><%= link_to message.user.username, "#", target: '_blank' %> dice
      <small class="text-muted">[at <%= message.created_at.strftime('%-d %B %Y, %H:%M:%S') %>]</small></h4>
    <p><%= message.content %></p>
  </div>
</li>

app/views/messages/create.js.erb
publisher = client.publish('/messages', {
  message: '<%= j render @message %>'
});

publisher.callback(function() {
  $('#message_body').val('');
  $('#new_message').find("input[type='submit']").val('Submit').prop('disabled', false)
});

publisher.errback(function() {
  alert('There was an error while posting your message.');
});

app/views/messages/destroy.html.erb
<h1>Messages#destroy</h1>
<p>Find me in app/views/messages/destroy.html.erb</p>

app/views/messages/index.js.erb
$('#messages').find('.media-list').html('<%= j render @messages %>');

app/views/messages/new.html.erb
<%= render 'form' %>
<div class="panel panel-default" id="messages">
  <div class="panel-body">
    <ul class="media-list">
      <%= render @messages %>
    </ul>
  </div>
</div>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>